// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Models;

namespace WebAPI.Migrations
{
    [DbContext(typeof(DonationDbContext))]
    partial class DonationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI.Models.DCandidate", b =>
                {
                    b.Property<int>("fID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("fAddress")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("fAge")
                        .HasColumnType("int");

                    b.Property<string>("fBloodGroup")
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("fEmail")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("fFullName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("fMobile")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("fID");

                    b.ToTable("DCandidates");
                });
#pragma warning restore 612, 618
        }
    }
}
