// <auto-generated />
using System;
using JQueryAjaxCRUDInCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JQueryAjaxCRUDInCore.Migrations
{
    [DbContext(typeof(TransactionDbContext))]
    [Migration("20201118062013_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JQueryAjaxCRUDInCore.Models.CTransaction", b =>
                {
                    b.Property<int>("fTranId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("fAccountNum")
                        .HasColumnType("nvarchar(12)");

                    b.Property<int>("fAmount")
                        .HasColumnType("int");

                    b.Property<string>("fBankName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("fBeneficiaryName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("fDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("fSwiftCode")
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("fTranId");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
